### ISSUE TITLE
Unable to open Half Life from flathub Steam

### ISSUE THREAD

**Issue by hanaral** [flathub/com.kristianduske.TrenchBroom#4]
After poking a hole in the trenchbroom flatpak so it can access the half  life game dir, picking the executable only throws this error message
![Screenshot from 2020-12-15 23-02-03](https://user-images.githubusercontent.com/58219504/102283067-94f18f80-3f29-11eb-8484-3bfb43e03c7a.png)

Edit: Sorry for tagging you @Sinihopea , but this pretty buch renders the direct running feature useless

**Comment by Sinihopea** [comment]
Hmmm... Let me see if I can do something for you. I've been fairly busy this past month but it should ease up within upcoming weeks. After that I concentrate on other things. Sorry for the late reply. And don't worry about tagging. I didn't mind.

Can you tell more about your issue? Where is your game binaries located since I think I should have most of the /home/ open so that people can run the maps from the editor directly. I use it myself to test run my Daikatana maps.

I should add that I'm fairly new to maintaining a Flatpak. There are number of things I don't quite understand but I'm doing my best. Sorry.

**Comment by hanaral** [comment]
@Sinihopea It seems to give the same error with the deb version of trenchbroom, so I’m presuming the problem lies with trenchbroom accessing the game properly. I’m unable to launch half life at all via the game engine settings, but it doesn’t seem to want to accept the “valve” folder as the materials folder either.

**Comment by Sinihopea** [comment]
Sorry, I've been so busy that I haven't had time to think about this issue at all. It might be that since you're using Flatpak version of Steam, they have restricted the access in their Flatpak. I don't really know how to help you since I think I already allow most rights one might need in Trenchbroom Flatpak and then some. It's actually more open than it should be IMO. If the problem is in Trenchbroom then we can probably ask from @kduske if he has any ideas. But I'd ask from the guys who package Steam inside Flatpak if they have ideas about this. They're the people who most likely can then help me to fix the issue if Trenchbroom Flatpak has the problem.
